table_detection:
  model_path: './new_epoch_24.pth'
  config_path: './cascade_mask_rcnn_hrnetv2p_w32_20e.py'
  score_thr: 0.85
table_line:
  model_path: './table-line.h5'
  input_shape: [512, 512]
  hprob: 0.5
  vprob: 0.5
ocr:
  type: 'paddle'
  paddle:
    det_path: "./inference/ch_ppocr_server_v1.1_det_infer/"
    rec_path: "./inference/ch_ppocr_mobile_v1.1_rec_infer/"
  chineseocr:
    det_path: ""
    rec_path: ""
web:
  host: '0.0.0.0'
  port: 23333
